---
extends:
  - cozy-app/basics
  - plugin:node/recommended
rules:
  node/shebang: off
  no-param-reassign: off
  spaced-comment: off
settings:
  node:
    allowModules:
      - electron
      - "@gyselroth/windows-fsstat"
