// flow-typed signature: 0e40564d80be151a7cd75d1f853019bb
// flow-typed version: <<STUB>>/yargs_v17.3.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yargs/build/lib/argsert' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/command' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/completion-templates' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/completion' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/middleware' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/parse-command' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/typings/common-types' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/typings/yargs-parser-types' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/usage' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/apply-extends' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/is-promise' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/levenshtein' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/maybe-async-result' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/obj-filter' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/process-argv' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/set-blocking' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/utils/which-module' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/validation' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/yargs-factory' {
  declare module.exports: any;
}

declare module 'yargs/build/lib/yerror' {
  declare module.exports: any;
}

declare module 'yargs/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yargs/build/lib/argsert.js' {
  declare module.exports: $Exports<'yargs/build/lib/argsert'>;
}
declare module 'yargs/build/lib/command.js' {
  declare module.exports: $Exports<'yargs/build/lib/command'>;
}
declare module 'yargs/build/lib/completion-templates.js' {
  declare module.exports: $Exports<'yargs/build/lib/completion-templates'>;
}
declare module 'yargs/build/lib/completion.js' {
  declare module.exports: $Exports<'yargs/build/lib/completion'>;
}
declare module 'yargs/build/lib/middleware.js' {
  declare module.exports: $Exports<'yargs/build/lib/middleware'>;
}
declare module 'yargs/build/lib/parse-command.js' {
  declare module.exports: $Exports<'yargs/build/lib/parse-command'>;
}
declare module 'yargs/build/lib/typings/common-types.js' {
  declare module.exports: $Exports<'yargs/build/lib/typings/common-types'>;
}
declare module 'yargs/build/lib/typings/yargs-parser-types.js' {
  declare module.exports: $Exports<'yargs/build/lib/typings/yargs-parser-types'>;
}
declare module 'yargs/build/lib/usage.js' {
  declare module.exports: $Exports<'yargs/build/lib/usage'>;
}
declare module 'yargs/build/lib/utils/apply-extends.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/apply-extends'>;
}
declare module 'yargs/build/lib/utils/is-promise.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/is-promise'>;
}
declare module 'yargs/build/lib/utils/levenshtein.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/levenshtein'>;
}
declare module 'yargs/build/lib/utils/maybe-async-result.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/maybe-async-result'>;
}
declare module 'yargs/build/lib/utils/obj-filter.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/obj-filter'>;
}
declare module 'yargs/build/lib/utils/process-argv.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/process-argv'>;
}
declare module 'yargs/build/lib/utils/set-blocking.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/set-blocking'>;
}
declare module 'yargs/build/lib/utils/which-module.js' {
  declare module.exports: $Exports<'yargs/build/lib/utils/which-module'>;
}
declare module 'yargs/build/lib/validation.js' {
  declare module.exports: $Exports<'yargs/build/lib/validation'>;
}
declare module 'yargs/build/lib/yargs-factory.js' {
  declare module.exports: $Exports<'yargs/build/lib/yargs-factory'>;
}
declare module 'yargs/build/lib/yerror.js' {
  declare module.exports: $Exports<'yargs/build/lib/yerror'>;
}
declare module 'yargs/helpers/index' {
  declare module.exports: $Exports<'yargs/helpers'>;
}
declare module 'yargs/helpers/index.js' {
  declare module.exports: $Exports<'yargs/helpers'>;
}
