#!/bin/bash

# For ubuntu 64bit
# See https://github.com/rogerwang/node-webkit/wiki/The-solution-of-lacking-libudev.so.0
if [ ! -f /lib/x86_64-linux-gnu/libudev.so.0 ] && [ -f /lib/x86_64-linux-gnu/libudev.so.1 ];
then
    ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
fi

# For ubuntu 32bit
# See https://github.com/rogerwang/node-webkit/wiki/The-solution-of-lacking-libudev.so.0
if [ ! -f /lib/i386-linux-gnu/libudev.so.0 ] && [ -f /lib/i386-linux-gnu/libudev.so.1 ];
then
    ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
fi


# Link to the binary
rm -f /usr/bin/cozy-desktop
ln -s /opt/cozy-desktop/cozy-desktop /usr/bin/cozy-desktop
