name: macOS

# To debug a job, add the following step:
# - name: Debug with tmate
#   uses: mxschmitt/action-tmate@v3

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - '.github/workflows/linux.yaml'

env:
  COZY_DESKTOP_DIR: "${{ github.workspace }}/twake-desktop"
  COZY_STACK_STORAGE: "${{ github.workspace }}/storage"
  COZY_URL: "http://cozy.localhost:8080"
  COZY_PASSPHRASE: "cozy"
  GO111MODULE: "on"
  NO_BREAKPOINTS: "1"
  NODE_ENV: "test"
  COZY_DESKTOP_HEARTBEAT: "1000"
  DISPLAY: ":99.0"
  NODE_VERSION: "20.15.1"
  GO_VERSION: "1.19"
  COUCHDB_VERSION: "3.2.2"
  COUCHDB_USER: "admin"
  COUCHDB_PASSWORD: "password"
  OS_USERNAME: "${{ secrets.SWIFT_OS_USERNAME }}"
  OS_PASSWORD: "${{ secrets.SWIFT_OS_PASSWORD }}"
  OS_PROJECT_NAME: "${{ secrets.SWIFT_OS_PROJECT_NAME }}"
  OS_REGION_NAME: "GRA"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_NAME: "Default"
  OS_AUTH_URL: "https://auth.cloud.ovh.net/v3"
  OS_IDENTITY_API_VERSION: "3"

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@5df4e62aed82ea1f787d2a02ab3dbfcaa49ffdd1

  unit:
    needs: cancel
    runs-on: macos-26-intel
    name: Unit tests
    strategy:
      matrix:
        fs: ['APFS']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Restore Lima cache
        id: cache-lima
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup Docker
        uses: ./.github/actions/setup-docker
      - name: Save Lima cache
        if: ${{ steps.cache-lima.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup golang
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup python
        run: pip install setuptools
      - name: Setup DNS resolution for .localhost
        uses: ./.github/actions/setup-dnsmasq
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install:all
      - name: Save node_modules cache
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Setup local env
        env:
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: |
          hdiutil create -megabytes 50 -fs "$COZY_DESKTOP_FS" -volname twake-desktop "$COZY_DESKTOP_DIR"
          hdiutil attach "${COZY_DESKTOP_DIR}.dmg" -mountpoint "$COZY_DESKTOP_DIR"
          echo "NODE_ENV=test" > "${{ github.workspace }}/.env.test"
      - name: Setup cozy-stack
        run: docker compose up -d
      - name: Setup test config
        run: |
          until docker exec twake-desktop-stack /twake-desktop/test/setup.sh
          do
            echo "Waiting for cozy-stack to be running..."
            sleep 30
          done
      - name: Unit tests
        env:
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: yarn test:unit --forbid-only

  integration:
    needs: cancel
    runs-on: macos-26-intel
    name: Integration tests
    strategy:
      matrix:
        fs: ['APFS']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Restore Lima cache
        id: cache-lima
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup Docker
        uses: ./.github/actions/setup-docker
      - name: Save Lima cache
        if: ${{ steps.cache-lima.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup golang
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup python
        run: pip install setuptools
      - name: Setup DNS resolution for .localhost
        uses: ./.github/actions/setup-dnsmasq
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install:all
      - name: Save node_modules cache
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Setup local env
        env:
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: |
          hdiutil create -megabytes 50 -fs "$COZY_DESKTOP_FS" -volname twake-desktop "$COZY_DESKTOP_DIR"
          hdiutil attach "${COZY_DESKTOP_DIR}.dmg" -mountpoint "$COZY_DESKTOP_DIR"
          echo "NODE_ENV=test" > "${{ github.workspace }}/.env.test"
      - name: Setup cozy-stack
        run: docker compose up -d
      - name: Setup test config
        run: |
          until docker exec twake-desktop-stack /twake-desktop/test/setup.sh
          do
            echo "Waiting for cozy-stack to be running..."
            sleep 30
          done
      - name: Integration tests
        env:
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: yarn test:integration --forbid-only

  scenarios:
    needs: cancel
    runs-on: macos-26-intel
    name: Scenarios
    strategy:
      matrix:
        stopped_client: ['', 'STOPPED']
        fs: ['APFS', 'HFS+']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Restore Lima cache
        id: cache-lima
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup Docker
        uses: ./.github/actions/setup-docker
      - name: Save Lima cache
        if: ${{ steps.cache-lima.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-lima
        with:
          path: ~/Library/Caches/lima
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.cache-name }}-${{ hashFiles('.github/actions/setup-docker/action.yaml') }}
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup golang
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup python
        run: pip install setuptools
      - name: Setup DNS resolution for .localhost
        uses: ./.github/actions/setup-dnsmasq
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install:all
      - name: Save node_modules cache
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Setup local env
        env:
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: |
          until hdiutil create -megabytes 100 -fs "$COZY_DESKTOP_FS" -volname twake-desktop "$COZY_DESKTOP_DIR"
          do
            sleep 1
          done
          until hdiutil attach "${COZY_DESKTOP_DIR}.dmg" -mountpoint "$COZY_DESKTOP_DIR"
          do
            sleep 1
          done
          echo "NODE_ENV=test" > "${{ github.workspace }}/.env.test"
      - name: Setup cozy-stack
        run: docker compose up -d
      - name: Setup test config
        run: |
          until docker exec twake-desktop-stack /twake-desktop/test/setup.sh
          do
            echo "Waiting for cozy-stack to be running..."
            sleep 30
          done
      - name: Scenarios
        env:
          STOPPED_CLIENT: ${{ matrix.stopped_client == 'STOPPED' }}
          COZY_DESKTOP_FS: ${{ matrix.fs }}
        run: yarn test:scenarios --forbid-only

  build:
    needs: cancel
    name: Build packages
    strategy:
      matrix:
        os: [macos-26-intel, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache/restore@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup python
        run: pip install setuptools
      - name: Install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install:all
      - name: Save node_modules cache
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-${{ runner.arch }}-v${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Build assets
        run: yarn build
      - name: Build package
        uses: ./.github/actions/build-and-publish
        with:
          gh-token: "${{ secrets.github_token }}"
          mac-cert: "${{ secrets.mac_cert }}"
          mac-cert-password: "${{ secrets.mac_cert_password }}"
          apple-id: "${{ secrets.apple_id }}"
          apple-id-password: "${{ secrets.apple_id_password }}"
          apple-team-id: "${{ secrets.apple_team_id }}"
      - name: Save latest-mac.yml
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/dist/latest*.yml
          archive: false
          retention-days: 5
      - name: Save dmg
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/dist/Twake[- ]Desktop[- ]*.dmg
          archive: false
          retention-days: 5
      - name: Save zip
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/dist/Twake[- ]Desktop[- ]*.zip
          archive: false
          retention-days: 5

