name: Publish to WinGet
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - if: github.event_name == 'released'
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: CozyCloud.CozyDrive
          token: ${{ secrets.WINGET_TOKEN }}
      - if: github.event_name == 'prereleased'
        uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: CozyCloud.CozyDrive.Beta
          version-regex: '(?<=v).*'
          token: ${{ secrets.WINGET_TOKEN }}
